format = """
[](#2C1A12)\
$python\
$username\
[](bg:#4E342E fg:#2C1A12)\
$directory\
[](fg:#4E342E bg:#6D4C41)\
$git_branch\
$git_status\
[](fg:#6D4C41 bg:#D84315)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#D84315 bg:#F9A825)\
$docker_context\
[](fg:#F9A825 bg:#880E4F)\
$time\
[ ](fg:#880E4F)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2C1A12"
style_root = "bg:#2C1A12"
format = '[$user ]($style)'

[directory]
style = "bg:#4E342E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#F9A825"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#6D4C41"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#6D4C41"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#2C1A12"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#D84315"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#880E4F"
format = '[ $time ]($style)'
