format = """
[](#5D1F14)\
$python\
$username\
[](bg:#85421F fg:#5D1F14)\
$directory\
[](fg:#85421F bg:#854E14)\
$git_branch\
$git_status\
[](fg:#854E14 bg:#C8601F)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#C8601F bg:#C08C39)\
$docker_context\
[](fg:#C08C39 bg:#5D1F14)\
$time\
[ ](fg:#5D1F14)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#5D1F14"
style_root = "bg:#5D1F14"
format = '[$user ]($style)'

[directory]
style = "bg:#85421F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#C08C39"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#854E14"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#854E14"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#5D1F14"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#C8601F"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5D1F14"
format = '[ $time ]($style)'
